# Generated by Django 5.2.6 on 2026-01-25 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneacionClaseGaide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=255)),
                ('competencia', models.TextField()),
                ('objetivo_aprendizaje', models.TextField()),
                ('duracion_clase', models.CharField(max_length=100)),
                ('nivel_grupo', models.CharField(max_length=100)),
                ('informacion_adicional', models.TextField(blank=True, null=True)),
                ('contenido_generado', models.TextField(blank=True, null=True)),
                ('fase_guide_json', models.JSONField(blank=True, null=True)),
                ('historial_refinamientos', models.JSONField(blank=True, null=True)),
                ('intentos_refinamiento', models.IntegerField(default=0)),
                ('publicada', models.BooleanField(default=False)),
                ('planeacion_finalizada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planeaciones_de_clases_planeacionclasegaide',
                'indexes': [models.Index(fields=['autor'], name='idx_planeacion_autor')],
            },
        ),
    ]
