# Generated by Django 5.2.6 on 2026-02-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeaciones_de_clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeacionclasegaide',
            name='area',
            field=models.CharField(choices=[('Español / Castellano', 'Español / Castellano'), ('Matemáticas', 'Matemáticas'), ('Ingles', 'Ingles'), ('Sociales', 'Sociales'), ('Ciencias Naturales', 'Ciencias Naturales'), ('Educación Física', 'Educación Física'), ('Filosofía', 'Filosofía'), ('Artística', 'Artística'), ('Ética y Valores', 'Ética y Valores'), ('Informática', 'Informática')], max_length=100),
        ),
        migrations.AlterField(
            model_name='planeacionclasegaide',
            name='grado',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Once')], default='1', max_length=2),
        ),
    ]
