# Generated by Django 5.2.6 on 2026-02-03 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planeaciones_de_clases', '0002_alter_planeacionclasegaide_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioPlaneacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_planeacion', to=settings.AUTH_USER_MODEL)),
                ('planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='planeaciones_de_clases.planeacionclasegaide')),
            ],
            options={
                'db_table': 'comentarios_planeacion',
                'indexes': [models.Index(fields=['planeacion'], name='idx_comentarios_planeacion')],
            },
        ),
        migrations.CreateModel(
            name='LikePlaneacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='planeaciones_de_clases.planeacionclasegaide')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_planeacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes_planeacion',
                'constraints': [models.UniqueConstraint(fields=('planeacion', 'usuario'), name='unique_like_usuario_planeacion')],
            },
        ),
    ]
